# Generated by Django 2.2.5 on 2021-09-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='superuser',
            new_name='superhost',
        ),
    ]
